# Generated by Django 4.1.5 on 2023-02-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomMember',
        ),
    ]
