# Generated by Django 4.1.5 on 2023-02-04 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RoomMember',
        ),
    ]
